export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_USERS = 'FETCH_USERS';
export const USER_CREATE = 'USER_CREATE';
export const USER_READ = 'USER_READ';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_DELETE = 'USER_DELETE';

export const FETCH_BRANDS = 'FETCH_BRANDS';
export const FETCH_WOODS = 'FETCH_WOODS';
export const FETCH_GUITARS_BY_SELL = 'FETCH_GUITARS_BY_SELL';
export const FETCH_GUITARS_BY_ARRIVAL = 'FETCH_GUITARS_BY_ARRIVAL';
export const PRODUCT_CREATE = 'PRODUCT_CREATE';
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';

export const ERROR_AUTH = 'ERROR_AUTH';
export const ERROR_USER = 'ERROR_USER';
export const ERROR_PRODUCT = 'ERROR_PRODUCT';
export const CLEAR_ERROR = 'CLEAR_ERROR';
